---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu
  - name: centos
    driver_config:
      image: centos:6.6
      platform: centos

suites:
  - name: nginx
    run_list:
      - recipe[nginx]
    attributes:
